use_frameworks!

target 'SecurioFramework_Example' do
  pod 'SecurioFramework', :path => '../'

  target 'SecurioFramework_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
  end
end
